// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xpqmdyvctaozumwuoatf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwcW1keXZjdGFvenVtd3VvYXRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExMTQ1NDksImV4cCI6MjA1NjY5MDU0OX0.rH9OK_bmvx_RcHW1SPXXC12RTP9a9wjEWwyysf7Rdy4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);